// <auto-generated />
namespace S.A___BookRental_LTD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTYPEOFMEMBERSHIPTOUSERVIEWMODEL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTYPEOFMEMBERSHIPTOUSERVIEWMODEL));
        
        string IMigrationMetadata.Id
        {
            get { return "201906242031580_AddTYPEOFMEMBERSHIPTOUSERVIEWMODEL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
